stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
         
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.12.3'

      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Azure subscription 1 (92a23ff9-4506-4981-af48-d0832ba7eb21)'
          backendAzureRmResourceGroupName: 'terr'
          backendAzureRmStorageAccountName: 'terr'
          backendAzureRmContainerName: 'terrcontainer'            
          backendAzureRmKey: 'deploy.tfstate'  
          
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'validate'

 
  - stage: deploy 
    jobs:
      - deployment: deploy_terraform
        continueOnError: false
        environment: 'dev'
        strategy:
         runOnce:
           deploy:
             steps:
               - checkout: self
               - task: TerraformInstaller@0
                 inputs:
                   terraformVersion: '0.12.3'
                    
               
               - task: TerraformTaskV2@2
                 inputs:
                   provider: 'azurerm'
                   command: 'init'
                   backendServiceArm: 'Azure subscription 1 (92a23ff9-4506-4981-af48-d0832ba7eb21)'
                   backendAzureRmResourceGroupName: 'terr'
                   backendAzureRmStorageAccountName: 'terr'
                   backendAzureRmContainerName: 'terrcontainer'
                   backendAzureRmKey: 'deploy.tfstate'
               - task: AzureCLI@2
                 displayName: "Terraform"
                 inputs:
                   azureSubscription: 'Azure subscription 1 (92a23ff9-4506-4981-af48-d0832ba7eb21)'
                   scriptType: bash
                   addSpnToEnvironment: true
                   scriptLocation: inlineScript
                   inlineScript: |
                      export ARM_CLIENT_ID=$(clientid)
                      export ARM_CLIENT_SECRET=$(clientsecret)
                      export ARM_TENANT_ID=$(tenantid)    
               - task: AzureCLI@2
                 displayName: "Terraform"
                 inputs:
                   azureSubscription: 'terraform'
                   scriptType: bash
                   addSpnToEnvironment: true
                   scriptLocation: inlineScript
                   inlineScript: terraform import azurerm_resource_group.app /subscriptions/92a23ff9-4506-4981-af48-d0832ba7eb21/resourceGroups/app01     
               - task: TerraformTaskV2@2
                 inputs:
                   provider: 'azurerm'
                   command: 'plan'
                   environmentServiceNameAzureRM: 'Azure subscription 1 (92a23ff9-4506-4981-af48-d0832ba7eb21)'
               - task: TerraformTaskV2@2
                 inputs:
                   provider: 'azurerm'
                   command: 'apply'
                   environmentServiceNameAzureRM: 'Azure subscription 1 (92a23ff9-4506-4981-af48-d0832ba7eb21)'
               